import React, { useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import {
  Mail,
  Calendar,
  Receipt,
  Users,
  BarChart3,
  Zap,
  Shield,
  Clock,
  ArrowRight,
  Check,
  ChevronDown,
  ChevronUp,
  Star,
  Menu,
  X,
  Sparkles,
  Globe,
  Bot,
  Play,
} from 'lucide-react'
import { useAuth } from '../context/AuthContext'

/* ------------------------------------------------------------------ */
/*  Data                                                               */
/* ------------------------------------------------------------------ */

const FEATURES = [
  {
    icon: Mail,
    title: 'Smart Inbox',
    desc: 'AI classifies, summarizes, and drafts replies for every email',
    color: 'text-blue-500',
    bg: 'bg-blue-500/10 dark:bg-blue-500/20',
  },
  {
    icon: Calendar,
    title: 'AI Calendar',
    desc: 'Meeting prep briefs generated automatically with client context',
    color: 'text-violet-500',
    bg: 'bg-violet-500/10 dark:bg-violet-500/20',
  },
  {
    icon: Receipt,
    title: 'Invoice Tracker',
    desc: 'Track payments, predict late payers, auto-send reminders',
    color: 'text-emerald-500',
    bg: 'bg-emerald-500/10 dark:bg-emerald-500/20',
  },
  {
    icon: Users,
    title: 'CRM Pipeline',
    desc: 'Drag-and-drop pipeline with AI client enrichment',
    color: 'text-amber-500',
    bg: 'bg-amber-500/10 dark:bg-amber-500/20',
  },
  {
    icon: BarChart3,
    title: 'AI Reports',
    desc: 'Daily briefings and weekly reports generated by AI',
    color: 'text-rose-500',
    bg: 'bg-rose-500/10 dark:bg-rose-500/20',
  },
  {
    icon: Zap,
    title: 'Automations',
    desc: 'Set it and forget it workflows that handle the admin work',
    color: 'text-cyan-500',
    bg: 'bg-cyan-500/10 dark:bg-cyan-500/20',
  },
]

const STEPS = [
  {
    num: '01',
    icon: Globe,
    title: 'Connect Your Tools',
    desc: 'Link Gmail, Calendar, Stripe, and Slack in one click',
  },
  {
    num: '02',
    icon: Bot,
    title: 'AI Organizes Everything',
    desc: 'Our AI classifies emails, preps meetings, and tracks invoices',
  },
  {
    num: '03',
    icon: Sparkles,
    title: 'You Focus on What Matters',
    desc: 'Get a morning briefing and let automations handle the rest',
  },
]

const METRICS = [
  { value: '93%', label: 'Time Saved on Admin', icon: Clock },
  { value: '50+', label: 'Automations Available', icon: Zap },
  { value: '10,000+', label: 'Emails Classified', icon: Mail },
  { value: '500+', label: 'Businesses Powered', icon: Users },
]

const PLANS = [
  {
    name: 'Free',
    price: '0',
    period: '/month',
    desc: 'Get started with the essentials',
    popular: false,
    cta: 'Start Free',
    features: [
      '1 email account',
      '5 clients',
      'Basic AI reports',
      'Community support',
      'Morning briefing',
    ],
  },
  {
    name: 'Pro',
    price: '49',
    period: '/month',
    desc: 'Everything you need to grow',
    popular: true,
    cta: 'Start Pro Trial',
    features: [
      'Unlimited email accounts',
      'Unlimited clients',
      'All integrations',
      'AI reports & analytics',
      'Slack bot',
      'Priority support',
      'Custom automations',
    ],
  },
  {
    name: 'Business',
    price: '149',
    period: '/month',
    desc: 'For teams and agencies',
    popular: false,
    cta: 'Contact Sales',
    features: [
      'Everything in Pro',
      'Team members (up to 10)',
      'Custom automations',
      'API access',
      'Dedicated account manager',
      'SSO & advanced security',
      'SLA guarantee',
    ],
  },
]

const FAQS = [
  {
    q: 'What is LytheraHub?',
    a: 'LytheraHub is an AI-powered business operations dashboard that connects all your tools — email, calendar, invoices, CRM, and more — into a single command center. It uses advanced AI to automate admin work, generate reports, and keep your business running smoothly.',
  },
  {
    q: 'Do I need to connect all my tools?',
    a: 'No, start with just one integration and add more whenever you\'re ready. LytheraHub works with Gmail, Google Calendar, Stripe, Slack, and more. Each integration unlocks new automation capabilities, but even a single connection provides immediate value.',
  },
  {
    q: 'Is my data secure?',
    a: 'Yes, we use enterprise-grade encryption at rest and in transit. All data is isolated per account in a multi-tenant architecture. We never share your data with third parties, and you can export or delete your data at any time. We are SOC 2 compliant.',
  },
  {
    q: 'Can I try it for free?',
    a: 'Yes, our free plan includes one email account, five clients, basic AI reports, and a daily morning briefing — no credit card required. You can upgrade to Pro at any time to unlock unlimited capabilities.',
  },
  {
    q: 'How does the AI work?',
    a: 'We use advanced AI models to analyze your emails, meetings, invoices, and client interactions. The AI classifies incoming messages, generates meeting prep briefs, predicts payment timelines, drafts replies, and compiles daily and weekly business reports — all tailored to your specific context.',
  },
  {
    q: 'Can I cancel anytime?',
    a: 'Yes, no long-term contracts or hidden fees. You can downgrade to the free plan or cancel entirely at any time from your Settings page. If you cancel a paid plan, you keep access until the end of your current billing period.',
  },
]

const FOOTER_LINKS = {
  Product: [
    { label: 'Features', href: '#features' },
    { label: 'Pricing', href: '#pricing' },
    { label: 'Demo', href: '/dashboard' },
    { label: 'API', href: '#' },
  ],
  Company: [
    { label: 'About', href: '#' },
    { label: 'Blog', href: '#' },
    { label: 'Careers', href: '#' },
    { label: 'Contact', href: '#' },
  ],
  Legal: [
    { label: 'Privacy', href: '#' },
    { label: 'Terms', href: '#' },
    { label: 'Security', href: '#' },
  ],
}

/* ------------------------------------------------------------------ */
/*  Sub-components                                                     */
/* ------------------------------------------------------------------ */

function FAQItem({ question, answer }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="border border-slate-200 dark:border-slate-700 rounded-xl overflow-hidden transition-colors">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left bg-white dark:bg-slate-800/50 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors cursor-pointer"
      >
        <span className="text-base font-semibold text-slate-900 dark:text-white">
          {question}
        </span>
        {open ? (
          <ChevronUp className="w-5 h-5 shrink-0 text-slate-400" />
        ) : (
          <ChevronDown className="w-5 h-5 shrink-0 text-slate-400" />
        )}
      </button>
      <div
        className={`grid transition-all duration-300 ease-in-out ${
          open ? 'grid-rows-[1fr] opacity-100' : 'grid-rows-[0fr] opacity-0'
        }`}
      >
        <div className="overflow-hidden">
          <p className="px-6 pb-5 pt-0 text-slate-600 dark:text-slate-400 leading-relaxed">
            {answer}
          </p>
        </div>
      </div>
    </div>
  )
}

function PricingCard({ plan, onStartFree }) {
  const popular = plan.popular

  return (
    <div
      className={`relative flex flex-col rounded-2xl border p-8 transition-all duration-300 hover:shadow-xl hover:-translate-y-1 ${
        popular
          ? 'border-brand-500 bg-white dark:bg-slate-800 shadow-lg shadow-brand-500/10 scale-[1.02] lg:scale-105'
          : 'border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800/60'
      }`}
    >
      {popular && (
        <div className="absolute -top-3.5 left-1/2 -translate-x-1/2">
          <span className="inline-flex items-center gap-1 rounded-full bg-brand-600 px-4 py-1 text-xs font-bold uppercase tracking-wider text-white shadow-md">
            <Star className="w-3 h-3 fill-current" /> Most Popular
          </span>
        </div>
      )}

      <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
        {plan.name}
      </h3>
      <p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{plan.desc}</p>

      <div className="mt-6 flex items-baseline gap-1">
        <span className="text-4xl font-extrabold text-slate-900 dark:text-white">
          &euro;{plan.price}
        </span>
        <span className="text-slate-500 dark:text-slate-400 text-sm">
          {plan.period}
        </span>
      </div>

      <ul className="mt-8 flex flex-col gap-3 flex-1">
        {plan.features.map((f) => (
          <li key={f} className="flex items-start gap-2.5 text-sm text-slate-700 dark:text-slate-300">
            <Check className="w-4 h-4 mt-0.5 shrink-0 text-brand-500" />
            {f}
          </li>
        ))}
      </ul>

      <button
        onClick={plan.name === 'Free' || plan.name === 'Pro' ? onStartFree : undefined}
        className={`mt-8 w-full py-3 px-6 rounded-xl text-sm font-semibold transition-all duration-200 cursor-pointer ${
          popular
            ? 'bg-brand-600 text-white hover:bg-brand-700 shadow-md shadow-brand-600/25 hover:shadow-lg hover:shadow-brand-600/30'
            : 'bg-slate-100 dark:bg-slate-700 text-slate-900 dark:text-white hover:bg-slate-200 dark:hover:bg-slate-600'
        }`}
      >
        {plan.cta}
      </button>
    </div>
  )
}

/* ------------------------------------------------------------------ */
/*  Landing Page                                                       */
/* ------------------------------------------------------------------ */

export default function Landing() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false)
  const { loginDemo } = useAuth()
  const navigate = useNavigate()

  const handleStartFree = async () => {
    try {
      await loginDemo()
      navigate('/dashboard')
    } catch {
      navigate('/dashboard')
    }
  }

  const scrollTo = (id) => {
    setMobileMenuOpen(false)
    const el = document.getElementById(id)
    if (el) el.scrollIntoView({ behavior: 'smooth' })
  }

  return (
    <div className="min-h-screen bg-white dark:bg-slate-950 text-slate-900 dark:text-white overflow-x-hidden">
      {/* ============================================================ */}
      {/*  NAVIGATION                                                   */}
      {/* ============================================================ */}
      <nav className="sticky top-0 z-50 w-full border-b border-slate-200/60 dark:border-slate-800/60 bg-white/80 dark:bg-slate-950/80 backdrop-blur-xl">
        <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
          {/* Logo */}
          <Link
            to="/"
            className="flex items-center gap-2 text-xl font-bold text-slate-900 dark:text-white"
          >
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-white">
              <Zap className="h-4.5 w-4.5" />
            </div>
            LytheraHub
          </Link>

          {/* Desktop nav */}
          <div className="hidden md:flex items-center gap-8">
            <button onClick={() => scrollTo('features')} className="text-sm font-medium text-slate-600 dark:text-slate-300 hover:text-brand-600 dark:hover:text-brand-400 transition-colors cursor-pointer">
              Features
            </button>
            <button onClick={() => scrollTo('pricing')} className="text-sm font-medium text-slate-600 dark:text-slate-300 hover:text-brand-600 dark:hover:text-brand-400 transition-colors cursor-pointer">
              Pricing
            </button>
            <button onClick={() => scrollTo('faq')} className="text-sm font-medium text-slate-600 dark:text-slate-300 hover:text-brand-600 dark:hover:text-brand-400 transition-colors cursor-pointer">
              FAQ
            </button>
          </div>

          {/* Desktop actions */}
          <div className="hidden md:flex items-center gap-3">
            <Link
              to="/login"
              className="text-sm font-medium text-slate-600 dark:text-slate-300 hover:text-brand-600 dark:hover:text-brand-400 transition-colors px-3 py-2"
            >
              Sign In
            </Link>
            <button
              onClick={handleStartFree}
              className="inline-flex items-center gap-2 rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white shadow-md shadow-brand-600/25 hover:bg-brand-700 hover:shadow-lg hover:shadow-brand-600/30 transition-all duration-200 cursor-pointer"
            >
              Start Free
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>

          {/* Mobile hamburger */}
          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="md:hidden p-2 rounded-lg text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer"
            aria-label="Toggle menu"
          >
            {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>

        {/* Mobile menu */}
        <div
          className={`md:hidden border-t border-slate-200/60 dark:border-slate-800/60 bg-white dark:bg-slate-950 transition-all duration-300 ${
            mobileMenuOpen
              ? 'max-h-80 opacity-100'
              : 'max-h-0 opacity-0 overflow-hidden'
          }`}
        >
          <div className="flex flex-col gap-1 px-4 py-4">
            <button onClick={() => scrollTo('features')} className="text-left px-3 py-2.5 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer">
              Features
            </button>
            <button onClick={() => scrollTo('pricing')} className="text-left px-3 py-2.5 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer">
              Pricing
            </button>
            <button onClick={() => scrollTo('faq')} className="text-left px-3 py-2.5 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors cursor-pointer">
              FAQ
            </button>
            <hr className="my-2 border-slate-200 dark:border-slate-800" />
            <Link to="/login" className="px-3 py-2.5 rounded-lg text-sm font-medium text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
              Sign In
            </Link>
            <button
              onClick={handleStartFree}
              className="mt-1 w-full rounded-xl bg-brand-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-brand-700 transition-colors cursor-pointer"
            >
              Start Free
            </button>
          </div>
        </div>
      </nav>

      {/* ============================================================ */}
      {/*  HERO SECTION                                                 */}
      {/* ============================================================ */}
      <section className="relative isolate overflow-hidden">
        {/* Background gradient decoration */}
        <div className="pointer-events-none absolute inset-0 -z-10">
          <div className="absolute -top-40 -right-40 h-[600px] w-[600px] rounded-full bg-brand-400/20 dark:bg-brand-600/10 blur-3xl" />
          <div className="absolute -bottom-40 -left-40 h-[500px] w-[500px] rounded-full bg-violet-400/20 dark:bg-violet-600/10 blur-3xl" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 h-[800px] w-[800px] rounded-full bg-cyan-400/10 dark:bg-cyan-600/5 blur-3xl" />
        </div>

        {/* Grid pattern overlay */}
        <div
          className="pointer-events-none absolute inset-0 -z-10 opacity-[0.03] dark:opacity-[0.05]"
          style={{
            backgroundImage:
              'linear-gradient(to right, currentColor 1px, transparent 1px), linear-gradient(to bottom, currentColor 1px, transparent 1px)',
            backgroundSize: '64px 64px',
          }}
        />

        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 pt-20 pb-24 sm:pt-28 sm:pb-32 lg:pt-36 lg:pb-40">
          <div className="mx-auto max-w-3xl text-center">
            {/* Badge */}
            <div className="mb-8 inline-flex items-center gap-2 rounded-full border border-brand-200 dark:border-brand-800 bg-brand-50 dark:bg-brand-950 px-4 py-1.5 text-sm font-medium text-brand-700 dark:text-brand-300">
              <Sparkles className="w-4 h-4" />
              AI-Powered Business Operations
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold tracking-tight text-slate-900 dark:text-white leading-[1.1]">
              Your Business on{' '}
              <span className="bg-gradient-to-r from-brand-600 via-violet-600 to-cyan-500 bg-clip-text text-transparent">
                Autopilot
              </span>
            </h1>

            <p className="mt-6 text-lg sm:text-xl leading-relaxed text-slate-600 dark:text-slate-400 max-w-2xl mx-auto">
              One AI-powered dashboard that connects your email, calendar, invoices,
              and clients. Stop switching tabs. Start running your business.
            </p>

            {/* CTA buttons */}
            <div className="mt-10 flex flex-col sm:flex-row items-center justify-center gap-4">
              <button
                onClick={handleStartFree}
                className="group inline-flex items-center gap-2 rounded-xl bg-brand-600 px-8 py-3.5 text-base font-semibold text-white shadow-lg shadow-brand-600/25 hover:bg-brand-700 hover:shadow-xl hover:shadow-brand-600/30 transition-all duration-200 cursor-pointer"
              >
                Start Free
                <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
              </button>
              <button
                onClick={() => scrollTo('features')}
                className="group inline-flex items-center gap-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 px-8 py-3.5 text-base font-semibold text-slate-700 dark:text-slate-300 hover:border-slate-400 dark:hover:border-slate-600 hover:bg-slate-50 dark:hover:bg-slate-800 transition-all duration-200 cursor-pointer"
              >
                <Play className="w-4 h-4" />
                Watch Demo
              </button>
            </div>

            {/* Subtle trust */}
            <p className="mt-6 text-sm text-slate-400 dark:text-slate-500">
              No credit card required &middot; Free forever plan &middot; Setup in 2 minutes
            </p>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  FEATURES GRID                                                */}
      {/* ============================================================ */}
      <section id="features" className="relative py-24 sm:py-32 bg-slate-50/50 dark:bg-slate-900/50">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          {/* Section heading */}
          <div className="mx-auto max-w-2xl text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 dark:text-white">
              Everything You Need,{' '}
              <span className="text-brand-600 dark:text-brand-400">One Dashboard</span>
            </h2>
            <p className="mt-4 text-lg text-slate-600 dark:text-slate-400">
              Six powerful modules that work together to automate your entire
              business operations stack.
            </p>
          </div>

          {/* Grid */}
          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {FEATURES.map((f) => {
              const Icon = f.icon
              return (
                <div
                  key={f.title}
                  className="group relative rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-8 transition-all duration-300 hover:shadow-xl hover:shadow-slate-200/50 dark:hover:shadow-slate-900/50 hover:-translate-y-1 hover:border-brand-200 dark:hover:border-brand-800"
                >
                  <div
                    className={`inline-flex items-center justify-center w-12 h-12 rounded-xl ${f.bg} transition-transform duration-300 group-hover:scale-110`}
                  >
                    <Icon className={`w-6 h-6 ${f.color}`} />
                  </div>
                  <h3 className="mt-5 text-lg font-semibold text-slate-900 dark:text-white">
                    {f.title}
                  </h3>
                  <p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-400">
                    {f.desc}
                  </p>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  HOW IT WORKS                                                 */}
      {/* ============================================================ */}
      <section className="py-24 sm:py-32">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 dark:text-white">
              Up and Running in{' '}
              <span className="text-brand-600 dark:text-brand-400">3 Steps</span>
            </h2>
            <p className="mt-4 text-lg text-slate-600 dark:text-slate-400">
              Connect your tools, let AI do the heavy lifting, and get your time back.
            </p>
          </div>

          <div className="grid gap-8 md:grid-cols-3">
            {STEPS.map((s, idx) => {
              const Icon = s.icon
              return (
                <div key={s.num} className="relative text-center">
                  {/* Connector line (hidden on mobile, shown between steps on desktop) */}
                  {idx < STEPS.length - 1 && (
                    <div className="hidden md:block absolute top-10 left-[calc(50%+40px)] w-[calc(100%-80px)] h-px bg-gradient-to-r from-brand-300 dark:from-brand-700 to-transparent" />
                  )}

                  <div className="relative inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-brand-50 dark:bg-brand-950 border border-brand-200 dark:border-brand-800 mb-6 transition-transform duration-300 hover:scale-105">
                    <Icon className="w-8 h-8 text-brand-600 dark:text-brand-400" />
                    <span className="absolute -top-2 -right-2 flex items-center justify-center w-7 h-7 rounded-full bg-brand-600 text-white text-xs font-bold shadow-md">
                      {s.num.replace('0', '')}
                    </span>
                  </div>

                  <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
                    {s.title}
                  </h3>
                  <p className="mt-2 text-sm text-slate-600 dark:text-slate-400 max-w-xs mx-auto leading-relaxed">
                    {s.desc}
                  </p>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  SOCIAL PROOF / METRICS                                       */}
      {/* ============================================================ */}
      <section className="py-20 bg-gradient-to-br from-brand-600 via-brand-700 to-violet-700 dark:from-brand-900 dark:via-brand-950 dark:to-violet-950">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {METRICS.map((m) => {
              const Icon = m.icon
              return (
                <div key={m.label} className="text-center">
                  <div className="inline-flex items-center justify-center w-12 h-12 rounded-xl bg-white/10 mb-4">
                    <Icon className="w-6 h-6 text-white/80" />
                  </div>
                  <div className="text-4xl sm:text-5xl font-extrabold text-white">
                    {m.value}
                  </div>
                  <div className="mt-2 text-sm font-medium text-brand-100 dark:text-brand-300">
                    {m.label}
                  </div>
                </div>
              )
            })}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  PRICING                                                      */}
      {/* ============================================================ */}
      <section id="pricing" className="py-24 sm:py-32 bg-slate-50/50 dark:bg-slate-900/50">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="mx-auto max-w-2xl text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 dark:text-white">
              Simple,{' '}
              <span className="text-brand-600 dark:text-brand-400">Transparent</span>{' '}
              Pricing
            </h2>
            <p className="mt-4 text-lg text-slate-600 dark:text-slate-400">
              Start free, upgrade when you need more. No surprises.
            </p>
          </div>

          <div className="grid gap-8 md:grid-cols-3 max-w-5xl mx-auto items-start">
            {PLANS.map((plan) => (
              <PricingCard key={plan.name} plan={plan} onStartFree={handleStartFree} />
            ))}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  FAQ                                                          */}
      {/* ============================================================ */}
      <section id="faq" className="py-24 sm:py-32">
        <div className="mx-auto max-w-3xl px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-3xl sm:text-4xl font-bold tracking-tight text-slate-900 dark:text-white">
              Frequently Asked{' '}
              <span className="text-brand-600 dark:text-brand-400">Questions</span>
            </h2>
            <p className="mt-4 text-lg text-slate-600 dark:text-slate-400">
              Everything you need to know about LytheraHub.
            </p>
          </div>

          <div className="flex flex-col gap-3">
            {FAQS.map((faq) => (
              <FAQItem key={faq.q} question={faq.q} answer={faq.a} />
            ))}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  CTA BANNER                                                   */}
      {/* ============================================================ */}
      <section className="py-20 sm:py-24">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-brand-600 via-brand-700 to-violet-700 dark:from-brand-800 dark:via-brand-900 dark:to-violet-900 px-8 py-16 sm:px-16 sm:py-20 text-center shadow-2xl shadow-brand-600/20">
            {/* Decorative elements */}
            <div className="pointer-events-none absolute -top-24 -right-24 h-64 w-64 rounded-full bg-white/10 blur-2xl" />
            <div className="pointer-events-none absolute -bottom-24 -left-24 h-64 w-64 rounded-full bg-white/10 blur-2xl" />

            <h2 className="relative text-3xl sm:text-4xl font-bold text-white">
              Ready to Put Your Business on Autopilot?
            </h2>
            <p className="relative mt-4 text-lg text-brand-100 max-w-xl mx-auto">
              Join hundreds of business owners who save hours every week with LytheraHub.
            </p>
            <button
              onClick={handleStartFree}
              className="relative mt-8 inline-flex items-center gap-2 rounded-xl bg-white px-8 py-3.5 text-base font-semibold text-brand-700 shadow-lg hover:bg-brand-50 transition-all duration-200 cursor-pointer group"
            >
              Get Started for Free
              <ArrowRight className="w-4 h-4 transition-transform group-hover:translate-x-1" />
            </button>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  FOOTER                                                       */}
      {/* ============================================================ */}
      <footer className="border-t border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-950">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
          <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-5">
            {/* Brand column */}
            <div className="lg:col-span-2">
              <Link to="/" className="flex items-center gap-2 text-xl font-bold text-slate-900 dark:text-white">
                <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-brand-600 text-white">
                  <Zap className="h-4.5 w-4.5" />
                </div>
                LytheraHub
              </Link>
              <p className="mt-4 text-sm text-slate-500 dark:text-slate-400 max-w-xs leading-relaxed">
                The AI-powered command center for modern businesses.
                Connect your tools, automate the busywork, and focus on growth.
              </p>
              {/* Social icons placeholder */}
              <div className="mt-6 flex items-center gap-3">
                {['X', 'LinkedIn', 'GitHub'].map((social) => (
                  <a
                    key={social}
                    href="#"
                    className="flex items-center justify-center w-9 h-9 rounded-lg bg-slate-100 dark:bg-slate-800 text-slate-500 dark:text-slate-400 hover:bg-brand-50 dark:hover:bg-brand-950 hover:text-brand-600 dark:hover:text-brand-400 transition-colors text-xs font-semibold"
                    aria-label={social}
                  >
                    {social[0]}
                  </a>
                ))}
              </div>
            </div>

            {/* Link columns */}
            {Object.entries(FOOTER_LINKS).map(([heading, links]) => (
              <div key={heading}>
                <h4 className="text-sm font-semibold text-slate-900 dark:text-white uppercase tracking-wider">
                  {heading}
                </h4>
                <ul className="mt-4 flex flex-col gap-3">
                  {links.map((l) => (
                    <li key={l.label}>
                      {l.href.startsWith('#') ? (
                        <button
                          onClick={() => {
                            if (l.href.length > 1) scrollTo(l.href.slice(1))
                          }}
                          className="text-sm text-slate-500 dark:text-slate-400 hover:text-brand-600 dark:hover:text-brand-400 transition-colors cursor-pointer"
                        >
                          {l.label}
                        </button>
                      ) : (
                        <Link
                          to={l.href}
                          className="text-sm text-slate-500 dark:text-slate-400 hover:text-brand-600 dark:hover:text-brand-400 transition-colors"
                        >
                          {l.label}
                        </Link>
                      )}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>

          {/* Bottom bar */}
          <div className="mt-12 pt-8 border-t border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4">
            <p className="text-sm text-slate-400 dark:text-slate-500">
              &copy; 2025 LytheraHub AI. All rights reserved.
            </p>
            <div className="flex items-center gap-1 text-sm text-slate-400 dark:text-slate-500">
              Built with
              <span className="mx-0.5 text-red-500">&hearts;</span>
              and a lot of AI
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}
